program = { SOI ~ functionDeclaration+ ~ EOI }

functionDeclaration = { "fn" ~ identifier ~ "(" ~ ")" ~ block }

block = { "{" ~ statement* ~ "}" }

statement = _{ (letStatement | assignmentStatement) ~ ";" }

letStatement = { "let" ~ identifier ~ "=" ~ expression }

assignmentStatement = { identifier ~ "=" ~ expression }

expression = { identifier  }

identifier = @{ XID_START ~ (XID_CONTINUE | "_")* }

WHITESPACE = _{ " " | "\t" | NEWLINE }
